### PR TITLE
Finally fixed Mac backend, support for notification scheduling

### PR DESCRIPTION
**Pull request by jendas1**
Hi, 
firstly thanks for your hard work. As you don't have mac I started to work on fixing the mac backend first and came with solution that is working fine. Also I found really useful scheduling notifications so I've added native support for osx backend and QTimer based support for all other backends (by implementing the function in SnoreBackend).
I hope that you will like the changes 😊.

### CODE REVIEW

**Comment by jendas1** [comment]
PS: I made also a small example for beginners on how to use this framework.

**Comment by TheOneRing** [comment]
Hi thank you for your work.

Would it be possible to split the pull request into multiple pull requests?
I think the scheduled notification stuff could be great but could need some discussion.

So the changes to the mac backend look really cool :smile:

**Comment by jendas1** [comment]
Sure, that's a good idea. I've just created a pull request only with mac notifications. Then I will add another one with explanation how does the scheduling work.

**Comment by TheOneRing** [comment]
Hi I think the example would be cool to add.
I now install a .pri file so it should be easier to use snorenotify with qmake projects.
https://github.com/Snorenotify/Snorenotify#how-to-integrate-snorenotify-in-your-project

**Comment by TheOneRing** [comment]
For scheduled notifications, I think it is cool if the backend supports them but I'm not sure if is so cool if snore needs to keep track of them and to use a qtimer.

**Comment by jendas1** [comment]
Hi, I made some improvements on Scheduling notification (mostly just renaming and resolving conflicts). For the qtimers: I've ment that even if the backend doesn't support scheduling, you can emulate this behaviour using qtimers. If backend supports scheduling you can override this methods and get rid of qtimers. So no matter which backend you have you can always use scheduling.

**Comment by jendas1** [comment]
And for keeping track of them: Suppose that this framework is used by simple countdown timer and you have scheduled the notification for the end. But you have to implement cancel button. How do you remove the scheduled notification if you don't keep track of them?

**Comment by jendas1** [comment]
PS: Check windows 8 notification api or apple NSUserNotification one. Both are able to remove scheduled notification.

**Comment by TheOneRing** [comment]
I would need to implement the scheduled notifications support in snore toast. but sounds good.
But I guess we should recommend to use it only with those backend really supporting it.

btw what is a valid use case? a calendar app?

**Comment by jendas1** [comment]
I've thought that the emulated (qtimer) scheduled notifications could work as a fallback (the same as for notifications the Snore backend). Valid use case could be all sorts of countdown timers (for example pomodoro) or apps that uses something like remind me in 10 minutes (that is used for os updates). Calendar app can also benefit from this feature. I am using it for countdown timer to notify the user how time he has.

**Comment by TheOneRing** [comment]
off topic but you more or less know the api^^.

currently I start a timeout

**Comment by TheOneRing** [comment]
sorry wrong button

**Comment by TheOneRing** [comment]
damned for windows toasts
- Desktop apps cannot schedule a toast

https://msdn.microsoft.com/en-us/library/windows/apps/hh779727.aspx

**Comment by jendas1** [comment]
Oh, that's not good. But I've found that requirements for scheduledToastNotification say that in windows 8 app putted in store are able to schedule notification and all windows platrforms running on windows 10. https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.notifications.scheduledtoastnotification.aspx .

**Comment by TheOneRing** [comment]
hm I tend to the conclusion that this is great for osx where it is supported, but misleading for all other backends as a notification is lost when the application is closed.

If your application should inform the user in 10 minutes you better use a qtimer on your side of the code.

I guess the best solution is to allow scheduled notifications, but assert or warn in backends not supporting scheduling and display the notifications directly and schedule on mac osx or backends supporting  it.

**Comment by TheOneRing** [comment]
oh and might it be possible that you can setup git with your name?
 git config --global user.name "<Your Name>"

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror a KDE repository. For this reason we can't accept contributions through Github. Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Pull request closed without merging**
